spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

server:
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}

logging:
  level:
    root: WARN
    com.financemanager: INFO
